"""add status column to submissions

Revision ID: 867b626e5ee2
Revises: f14fb96d581b
Create Date: 2026-09-05 16:10:57.462477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '867b626e5ee2'
down_revision: Union[str, Sequence[str], None] = 'f14fb96d581b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('submissions', sa.Column('status', sa.String(), nullable=False, server_default='pending'))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'status')
    # ### end Alembic commands ###
